---
# host: 
# port: 6379
user: paul
password: democracyIsFragile
database_name: paul
# ansible_become_pass: 

apt_packages:
  - apt-transport-https
  - ca-certificates
  - emacs-nox
  - git
  - curl
  - unzip
  - zsh
  - python
  - python-pip
  - python-psycopg2
  - nodejs
  - npm
  - maven
  - openjdk-11-jre