---
- name: PostGreSQL role
  hosts: postgresql
  become: yes
  tasks:
    - name: download postgresql 12
      apt:
        name: postgresql-12
        state: present
      notify:
        - Enable Postgresql
    - name: download postgresql tools
      apt:
        name: postgresql-client
        state: present
      notify:
        - Restart Postgresql
    - name: create user paul with password
      postgresql_user:
        db: paul
        user: paul
        password: "democracyIsFragile"
      notify:
        - Restart Postgresql
    - name: Create database paul with schema file
      - postgresql_db:
        name: paul
        state: dump
        target: ../files/schema.sql
        target_opts: "-n public"