---
- name: Download redis
  apt:
    name: redis
    state: present
  notify:
    - Start redis
- name: Copy redis.conf file
  copy: src=../files/redis.conf dest=/etc/redis/redis.conf group=redis owner=redis
  notify:
    - Restart redis
# - name: Change redis port and hostname
#   redis:
#     command: replica
#     master_host: "{{host}}"
#     master_port: "{{port}}"