---
- name: All hosts
  become: yes
  hosts: all
  roles:
    - base
- name: Redis host
  become: yes
  hosts: redis
  roles:
    - redis
- name: PostGreSQL host
  become: yes
  hosts: postgresql
  roles:
    - postgresql
- name: Poll host
  become: yes
  hosts: poll
  roles:
    - poll
- name: Result host
  become: yes
  hosts: result
  roles:
    - result
- name: Worker host
  become: yes
  hosts: worker
  roles:
    - worker